name: Docker Build RPM

on: [push]

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build a Docker image and RPM file
        run: ${{ github.workspace }}/scripts/docker_rpm.sh
      - name: Archive Results
        uses: actions/upload-artifact@v1
        with:
          name: rpmbuild
          path: rpmbuild

